version: '2'
services:
    familytreejhipster-app:
        image: familytreejhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://familytreejhipster-mariadb:3306/familytreejhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    familytreejhipster-mariadb:
        extends:
            file: mariadb.yml
            service: familytreejhipster-mariadb
